# Generated by Django 5.0.2 on 2024-03-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_django', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='fecha_completado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
